#!/bin/sh

#  These scripts are written by me. If you want to use them, feel free to. But don't take credit for them

 alert --warning "Would you like to make a BFS CD or an ISO9660 CD, or a pre-exsisting disc image?" "BFS" "ISO9660" "OTHER" 
 retval=$?
 if [ $retval -eq 0 ]
 then
 Terminal -t "Making BFS Image" /boot/home/config/bin/MakeBFS  #call the make image script
  sync  #sync
  mkdir /mnt
  mount /boot/home/image.img /mnt #make a mount dir, and mount the image
  alert --warning "Please copy all the files you want on the CD to the mounted Image. Title the image, and then unmount it. When that is done, cliick OK, and I will start making the CD." 
 Terminal -t "BFS CD Creation" /boot/home/config/bin/WriteBFS #call the write image script
fi

if [ $retval -eq 1 ]
 then
  mkdir /boot/home/cdromiso
  alert "Please copy the files you want on the ISO CD to /boot/home/cdromiso . After you are done, close the directory, and click OK" 
  Terminal -t "ISO CD Creation" /boot/home/config/bin/WriteISO
fi

if [ $retval -eq 2 ] 
   then 
    Terminal -t "Preparing to write pre-exsisting image" /boot/home/config/bin/WritePRE
fi