#!/bin/sh
read -p "Name of your ISO disk :" isoname  #read in the name
mkhybrid -a -r -J -V $isoname -o /boot/home/imageiso.img /boot/home/cdromiso/
alert "ARE YOU SURE? IF YOU DON'T WANT TO MAKE A CD, TAKE OUT THE BLANK CD!"
chmod -w /boot/home/imageiso.img
cdrecord -v dev=$CDRPOS speed=$CDRSPD -data /boot/home/imageiso.img 
chmod +w /boot/home/imageiso.img